# backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-backend
  labels:
    app: chat-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-backend
  template:
    metadata:
      labels:
        app: chat-backend
    spec:
      containers:
      - name: chat-backend
        image: adeshghadage/chatapp-backend:latest
        ports:
        - containerPort: 3001
        env:
        - name: PORT
          value: "3001"
        - name: MONGO_DB_URI
          value: "mongodb://mongo-service:27017/chat-app"
        - name: JWT_SECRET
          value: "AdeshSecret"
        - name: NODE_ENV
          value: "production"
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: chat-backend-service
spec:
  type: ClusterIP
  selector:
    app: chat-backend
  ports:
  - port: 3001
    targetPort: 3001