# backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-backend
  template:
    metadata:
      labels:
        app: chat-backend
    spec:
      containers:
      - name: chat-backend
        image: adeshghadage/chatapp-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        env:
        - name: MONGO_DB_URI
          value: mongodb://root:password@mongodb:27017/chatapp?authSource=admin
        - name: JWT_SECRET
          value: AdeshSecret
        - name: NODE_ENV
          value: production
---
apiVersion: v1
kind: Service
metadata:
  name: chat-backend
spec:
  selector:
    app: chat-backend
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001